// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0L94D-w_v9z_1CEr0w36dT3-L48cRHgo',
    appId: '1:531076052203:web:a6539bc54642a13b0bfaae',
    messagingSenderId: '531076052203',
    projectId: 'rent-ease-c777b',
    authDomain: 'rent-ease-c777b.firebaseapp.com',
    storageBucket: 'rent-ease-c777b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB86GrBz_shr8Ln42CjEdqTkwHZLOVDDsM',
    appId: '1:531076052203:android:dc886465ed5456df0bfaae',
    messagingSenderId: '531076052203',
    projectId: 'rent-ease-c777b',
    storageBucket: 'rent-ease-c777b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDzpGYJHd_68SVrFj-aflmhqZ_OtXeNuw',
    appId: '1:531076052203:ios:5ef11a1bf3364b680bfaae',
    messagingSenderId: '531076052203',
    projectId: 'rent-ease-c777b',
    storageBucket: 'rent-ease-c777b.appspot.com',
    iosBundleId: 'com.example.rentEase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDzpGYJHd_68SVrFj-aflmhqZ_OtXeNuw',
    appId: '1:531076052203:ios:3e69c46ecfbcd9e90bfaae',
    messagingSenderId: '531076052203',
    projectId: 'rent-ease-c777b',
    storageBucket: 'rent-ease-c777b.appspot.com',
    iosBundleId: 'com.example.rentEase.RunnerTests',
  );
}
